# Generated by Django 3.1.4 on 2020-12-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChristmasDecor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='decorationImages/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='decorationImages/')),
                ('image1_cover', models.ImageField(blank=True, null=True, upload_to='decorationImages/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='decorationImages/')),
                ('image2_cover', models.ImageField(blank=True, null=True, upload_to='decorationImages/')),
            ],
        ),
        migrations.CreateModel(
            name='Coverlate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='coverlateImages/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='coverlateImages/')),
                ('image1_cover', models.ImageField(blank=True, null=True, upload_to='coverlateImages/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='coverlateImages/')),
                ('image2_cover', models.ImageField(blank=True, null=True, upload_to='coverlateImages/')),
            ],
        ),
        migrations.CreateModel(
            name='EasterDecor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='decorationImages/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='decorationImages/')),
                ('image1_cover', models.ImageField(blank=True, null=True, upload_to='decorationImages/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='decorationImages/')),
                ('image2_cover', models.ImageField(blank=True, null=True, upload_to='decorationImages/')),
            ],
        ),
        migrations.CreateModel(
            name='Gobelin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='gobelinImages/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='gobelinImages/')),
                ('image1_cover', models.ImageField(blank=True, null=True, upload_to='gobelinImages/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='gobelinImages/')),
                ('image2_cover', models.ImageField(blank=True, null=True, upload_to='gobelinImages/')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('napkinImage', models.ImageField(blank=True, null=True, upload_to='homeImages/')),
                ('gobelinImage', models.ImageField(blank=True, null=True, upload_to='homeImages/')),
                ('tableclothImage', models.ImageField(blank=True, null=True, upload_to='homeImages/')),
                ('coverletImage', models.ImageField(blank=True, null=True, upload_to='homeImages/')),
                ('decorationImage', models.ImageField(blank=True, null=True, upload_to='homeImages/')),
            ],
        ),
        migrations.CreateModel(
            name='Napkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='napkinImages/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='napkinImages/')),
                ('image1_cover', models.ImageField(blank=True, null=True, upload_to='napkinImages/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='napkinImages/')),
                ('image2_cover', models.ImageField(blank=True, null=True, upload_to='napkinImages/')),
            ],
        ),
        migrations.CreateModel(
            name='Tablecloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='tableclothImages/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='tableclothImages/')),
                ('image1_cover', models.ImageField(blank=True, null=True, upload_to='tableclothImages/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='tableclothImages/')),
                ('image2_cover', models.ImageField(blank=True, null=True, upload_to='tableclothImages/')),
            ],
        ),
    ]
