# Generated by Django 3.1.4 on 2020-12-21 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChristmasDecor',
        ),
        migrations.DeleteModel(
            name='EasterDecor',
        ),
    ]
