# Generated by Django 3.1.4 on 2020-12-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20201222_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Christmas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='decorationImages/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='decorationImages/')),
                ('image1_cover', models.ImageField(blank=True, null=True, upload_to='decorationImages/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='decorationImages/')),
                ('image2_cover', models.ImageField(blank=True, null=True, upload_to='decorationImages/')),
            ],
        ),
    ]
