# Generated by Django 3.1.4 on 2020-12-22 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_easter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='christmas',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='christmas',
            name='image2_cover',
        ),
        migrations.RemoveField(
            model_name='easter',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='easter',
            name='image2_cover',
        ),
        migrations.RemoveField(
            model_name='gobelin',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='gobelin',
            name='image2_cover',
        ),
    ]
